//
//  MainWorker.swift
//  SwiftStudy
//
//  Created by hyukjun on 2021/07/14.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MainWorker
{
  func doSomeWork()
  {
  }
}
