//
//  RxSwiftPresenter.swift
//  SwiftStudy
//
//  Created by hyukjun on 2021/07/29.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RxSwiftPresentationLogic {
  func presentSomething(response: RxSwift.Something.Response)
}

class RxSwiftPresenter: RxSwiftPresentationLogic {
  weak var viewController: RxSwiftDisplayLogic?
  
  // MARK: Do something
  
    func presentSomething(response: RxSwift.Something.Response) {
    let viewModel = RxSwift.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
