//
//  RxSwiftRouter.swift
//  SwiftStudy
//
//  Created by hyukjun on 2021/07/29.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RxSwiftRoutingLogic {
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol RxSwiftDataPassing {
  var dataStore: RxSwiftDataStore? { get }
}

class RxSwiftRouter: NSObject, RxSwiftRoutingLogic, RxSwiftDataPassing {
  weak var viewController: RxSwiftViewController?
  var dataStore: RxSwiftDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: RxSwiftViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: RxSwiftDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
