//
//  MainViewController.swift
//  SwiftStudy
//
//  Created by hyukjun on 2021/07/14.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainDisplayLogic: class {
  func displaySomething(viewModel: Main.Something.ViewModel)
}

class MainViewController: UIViewController, MainDisplayLogic {
  var interactor: MainBusinessLogic?
  var router: (NSObjectProtocol & MainRoutingLogic & MainDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup() {
    let viewController = self
    let interactor = MainInteractor()
    let presenter = MainPresenter()
    let router = MainRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad() {
    super.viewDidLoad()
    self.navigationController?.setNavigationBarHidden(true, animated: false)
  }
  
  // MARK: Do something
  func doSomething() {
   
  }
  
  func displaySomething(viewModel: Main.Something.ViewModel) {
    
  }
    
    // MARK: 버튼 - onClickButton
    @IBAction func moveToSceneDelegate(_ sender: Any) {
        let page = TextFieldVC()
        self.navigationController?.pushViewController(page, animated: true)
    }
    
    @IBAction func moveToScrollView(_ sender: Any) {
        let page = ScrollVC1()
        self.navigationController?.pushViewController(page, animated: true)
//        self.present(page, animated: false)
    }

    @IBAction func moveToRxSwift(_ sender: Any) {
        let page = RxSwiftViewController()
        self.navigationController?.pushViewController(page, animated: true)
    }
    
    @IBAction func moveToTimerViewController(_ sender: Any) {
        let page = TimerViewController()
        self.navigationController?.pushViewController(page, animated: true)
    }

    @IBAction func moveToPageViewController(_ sender: Any) {
        let page = PageViewController()
        self.navigationController?.pushViewController(page, animated: false)
    }
    @IBAction func moveToPageStretchHeaderView(_ sender: Any) {
        let page = StretchCollectionViewVC()
        self.navigationController?.pushViewController(page, animated: false)
    }
    
    @IBAction func moveToStretchScrollView(_ sender: Any) {
        let page = StretchScrollView()
        self.navigationController?.pushViewController(page, animated: false)
    }
}
